# Contains a single run of an experiment
---
name: scale
experiments:
  - name: container-killer
    path: experiments/container-kill/

conditions:
  - name: Wget should work
    command: |
      wget -O - localhost:8080 --header="NSM-Color: blue"
    type: [pre, post]

aut:
  chart: 
    path: use_cases/scale/sfc-proxy
    name: scale
  values:
    passthrough.sfc_replicas: 3
    chaosdeploy: acl-filter-nse-blue