# Contains a single run of an experiment
---
name: scale
experiments:
  - name: pod-delete
    path: experiments/pod-delete/
    target: 
      ns: 'default'
      label: 'app=acl-filter'
      kind: 'deployment'
      container: 'acl-filter'

conditions:
  - name: Wget should work
    command: |
      wget -O - localhost:8080 --header="NSM-Color: blue"
    type: [pre, post]
    entrypoint:
      pod: proxy
      container: proxy-nsc

aut:
  chart: 
    path: use_cases/scale/sfc-proxy
    name: scale
  values:
    passthrough.sfc_replicas: 1..15
    chaosdeploy: acl-filter-nse-blue