# Contains a single run of an experiment
---
name: scale
experiments:
  - name: pod-delete
    path: experiments/pod-delete/
    target: 
      ns: 'default'
      label: 'app=enb'
      kind: 'deployment'
      container: 'enb'

conditions:
  - name: Wget should work
    command: |
      /bin/sh -c "wget -T 10 -t 1 -O - 10.60.1.1"
    type: [pre, post]
    entrypoint:
      pod: ue
      container: gogtp-ue

aut:
  chart: 
    path: use_cases/complexity/gogtp
    name: gogtp
  values:
    chaosdeploy: enb