---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "passthrough"
      networkservicemesh.io/impl: "web-service"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "passthrough"
        networkservicemesh.io/impl: "web-service"
    spec:
      containers:
        - name: passthrough
          image: nicoekkart/secure-intranet-vppagent-endpoint:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "web-service"
            - name: ENDPOINT_LABELS
              value: "app=passthrough-1"
            - name: CLIENT_NETWORK_SERVICE
              value: "web-service"
            - name: CLIENT_LABELS
              value: "app=passthrough-1"
            - name: TRACER_ENABLED
              value: "true"
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: passthrough-1
  annotations:
    reloader.stakater.com/auto: "true"