---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      networkservicemesh.io/app: "proxy-nsc"
      networkservicemesh.io/impl: "web-service"
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "proxy-nsc"
        networkservicemesh.io/impl: "web-service"
    spec:
      containers:
        - name: sidecar-nse
          image: nicoekkart/proxy-sidecar-nse:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "web-service"
            - name: ENDPOINT_LABELS
              value: "app=proxy-nsc"
            - name: TRACER_ENABLED
              value: "true"
            - name: IP_ADDRESS
              value: "10.60.0.0/24"
          resources:
            limits:
              networkservicemesh.io/socket: 1
        - name: proxy-nsc
          image: nicoekkart/sfc-proxy-proxy-nsc:latest
          imagePullPolicy: Always
          env:
            - name: CLIENT_NETWORK_SERVICE
              value: "web-service"
            - name: PROXY_HOST
              value: "0.0.0.0:8080"
          ports:
            - containerPort: 8080
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: proxy-nsc
  namespace: default
