---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: web-service
spec:
  payload: IP
  matches:
  # COLORS
{{- range $color_i, $color := $.Values.colors }}
    - match:
      sourceSelector:
        app: proxy
        color: {{$color}}
      route:
        - destination:
          destinationSelector:
            app: acl-filter
            color: {{$color}}
    - match:
      sourceSelector:
        app: acl-filter
        color: {{$color}}
      route:
        - destination:
          destinationSelector:
            app: passthrough-1
            color: {{$color}}


  {{ $count := sub $.Values.passthrough.sfc_replicas 1 | int }}
  {{ range $replica_i, $e := until $count }}
    - match:
      sourceSelector:
        app: passthrough-{{add $replica_i 1}}
        color: {{$color}}
      route:
        - destination:
          destinationSelector:
            app: passthrough-{{add $replica_i 2}}
            color: {{$color}}
  {{ end }}
    - match:
      sourceSelector:
        app: passthrough-{{ $.Values.passthrough.sfc_replicas }}
        color: {{$color}}
      route:
        - destination:
          destinationSelector:
            app: nginx
            color: {{$color}}
{{ end -}}
    # DEFAULT
    - match:
      sourceSelector:
        app: proxy
      route:
        - destination:
          destinationSelector:
            app: acl-filter